package com.whty.cms.base.pojo;

public class BaseFields {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_FIELDS.FIELD_ID
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    private String fieldId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_FIELDS.EN_FIELD_NAME
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    private String enFieldName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_FIELDS.FIELD_NAME
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    private String fieldName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_FIELDS.VALUE_FIELD
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    private String valueField;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_FIELDS.DISPLAY_FIELD
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    private String displayField;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_FIELDS.ENABLED_STATUS
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    private Short enabledStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_FIELDS.FIELD_SORT
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    private Short fieldSort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_FIELDS.FIELD_ID
     *
     * @return the value of BASE_FIELDS.FIELD_ID
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public String getFieldId() {
        return fieldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_FIELDS.FIELD_ID
     *
     * @param fieldId the value for BASE_FIELDS.FIELD_ID
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public void setFieldId(String fieldId) {
        this.fieldId = fieldId == null ? null : fieldId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_FIELDS.EN_FIELD_NAME
     *
     * @return the value of BASE_FIELDS.EN_FIELD_NAME
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public String getEnFieldName() {
        return enFieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_FIELDS.EN_FIELD_NAME
     *
     * @param enFieldName the value for BASE_FIELDS.EN_FIELD_NAME
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public void setEnFieldName(String enFieldName) {
        this.enFieldName = enFieldName == null ? null : enFieldName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_FIELDS.FIELD_NAME
     *
     * @return the value of BASE_FIELDS.FIELD_NAME
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_FIELDS.FIELD_NAME
     *
     * @param fieldName the value for BASE_FIELDS.FIELD_NAME
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName == null ? null : fieldName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_FIELDS.VALUE_FIELD
     *
     * @return the value of BASE_FIELDS.VALUE_FIELD
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public String getValueField() {
        return valueField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_FIELDS.VALUE_FIELD
     *
     * @param valueField the value for BASE_FIELDS.VALUE_FIELD
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public void setValueField(String valueField) {
        this.valueField = valueField == null ? null : valueField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_FIELDS.DISPLAY_FIELD
     *
     * @return the value of BASE_FIELDS.DISPLAY_FIELD
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public String getDisplayField() {
        return displayField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_FIELDS.DISPLAY_FIELD
     *
     * @param displayField the value for BASE_FIELDS.DISPLAY_FIELD
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public void setDisplayField(String displayField) {
        this.displayField = displayField == null ? null : displayField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_FIELDS.ENABLED_STATUS
     *
     * @return the value of BASE_FIELDS.ENABLED_STATUS
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public Short getEnabledStatus() {
        return enabledStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_FIELDS.ENABLED_STATUS
     *
     * @param enabledStatus the value for BASE_FIELDS.ENABLED_STATUS
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public void setEnabledStatus(Short enabledStatus) {
        this.enabledStatus = enabledStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_FIELDS.FIELD_SORT
     *
     * @return the value of BASE_FIELDS.FIELD_SORT
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public Short getFieldSort() {
        return fieldSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_FIELDS.FIELD_SORT
     *
     * @param fieldSort the value for BASE_FIELDS.FIELD_SORT
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public void setFieldSort(Short fieldSort) {
        this.fieldSort = fieldSort;
    }
}