package com.whty.cms.base.pojo;

import java.util.ArrayList;
import java.util.List;

public class BaseFieldsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BASE_FIELDS
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BASE_FIELDS
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BASE_FIELDS
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_FIELDS
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public BaseFieldsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_FIELDS
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_FIELDS
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_FIELDS
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_FIELDS
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_FIELDS
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_FIELDS
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_FIELDS
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_FIELDS
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_FIELDS
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASE_FIELDS
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BASE_FIELDS
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFieldIdIsNull() {
            addCriterion("FIELD_ID is null");
            return (Criteria) this;
        }

        public Criteria andFieldIdIsNotNull() {
            addCriterion("FIELD_ID is not null");
            return (Criteria) this;
        }

        public Criteria andFieldIdEqualTo(String value) {
            addCriterion("FIELD_ID =", value, "fieldId");
            return (Criteria) this;
        }

        public Criteria andFieldIdNotEqualTo(String value) {
            addCriterion("FIELD_ID <>", value, "fieldId");
            return (Criteria) this;
        }

        public Criteria andFieldIdGreaterThan(String value) {
            addCriterion("FIELD_ID >", value, "fieldId");
            return (Criteria) this;
        }

        public Criteria andFieldIdGreaterThanOrEqualTo(String value) {
            addCriterion("FIELD_ID >=", value, "fieldId");
            return (Criteria) this;
        }

        public Criteria andFieldIdLessThan(String value) {
            addCriterion("FIELD_ID <", value, "fieldId");
            return (Criteria) this;
        }

        public Criteria andFieldIdLessThanOrEqualTo(String value) {
            addCriterion("FIELD_ID <=", value, "fieldId");
            return (Criteria) this;
        }

        public Criteria andFieldIdLike(String value) {
            addCriterion("FIELD_ID like", value, "fieldId");
            return (Criteria) this;
        }

        public Criteria andFieldIdNotLike(String value) {
            addCriterion("FIELD_ID not like", value, "fieldId");
            return (Criteria) this;
        }

        public Criteria andFieldIdIn(List<String> values) {
            addCriterion("FIELD_ID in", values, "fieldId");
            return (Criteria) this;
        }

        public Criteria andFieldIdNotIn(List<String> values) {
            addCriterion("FIELD_ID not in", values, "fieldId");
            return (Criteria) this;
        }

        public Criteria andFieldIdBetween(String value1, String value2) {
            addCriterion("FIELD_ID between", value1, value2, "fieldId");
            return (Criteria) this;
        }

        public Criteria andFieldIdNotBetween(String value1, String value2) {
            addCriterion("FIELD_ID not between", value1, value2, "fieldId");
            return (Criteria) this;
        }

        public Criteria andEnFieldNameIsNull() {
            addCriterion("EN_FIELD_NAME is null");
            return (Criteria) this;
        }

        public Criteria andEnFieldNameIsNotNull() {
            addCriterion("EN_FIELD_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andEnFieldNameEqualTo(String value) {
            addCriterion("EN_FIELD_NAME =", value, "enFieldName");
            return (Criteria) this;
        }

        public Criteria andEnFieldNameNotEqualTo(String value) {
            addCriterion("EN_FIELD_NAME <>", value, "enFieldName");
            return (Criteria) this;
        }

        public Criteria andEnFieldNameGreaterThan(String value) {
            addCriterion("EN_FIELD_NAME >", value, "enFieldName");
            return (Criteria) this;
        }

        public Criteria andEnFieldNameGreaterThanOrEqualTo(String value) {
            addCriterion("EN_FIELD_NAME >=", value, "enFieldName");
            return (Criteria) this;
        }

        public Criteria andEnFieldNameLessThan(String value) {
            addCriterion("EN_FIELD_NAME <", value, "enFieldName");
            return (Criteria) this;
        }

        public Criteria andEnFieldNameLessThanOrEqualTo(String value) {
            addCriterion("EN_FIELD_NAME <=", value, "enFieldName");
            return (Criteria) this;
        }

        public Criteria andEnFieldNameLike(String value) {
            addCriterion("EN_FIELD_NAME like", value, "enFieldName");
            return (Criteria) this;
        }

        public Criteria andEnFieldNameNotLike(String value) {
            addCriterion("EN_FIELD_NAME not like", value, "enFieldName");
            return (Criteria) this;
        }

        public Criteria andEnFieldNameIn(List<String> values) {
            addCriterion("EN_FIELD_NAME in", values, "enFieldName");
            return (Criteria) this;
        }

        public Criteria andEnFieldNameNotIn(List<String> values) {
            addCriterion("EN_FIELD_NAME not in", values, "enFieldName");
            return (Criteria) this;
        }

        public Criteria andEnFieldNameBetween(String value1, String value2) {
            addCriterion("EN_FIELD_NAME between", value1, value2, "enFieldName");
            return (Criteria) this;
        }

        public Criteria andEnFieldNameNotBetween(String value1, String value2) {
            addCriterion("EN_FIELD_NAME not between", value1, value2, "enFieldName");
            return (Criteria) this;
        }

        public Criteria andFieldNameIsNull() {
            addCriterion("FIELD_NAME is null");
            return (Criteria) this;
        }

        public Criteria andFieldNameIsNotNull() {
            addCriterion("FIELD_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andFieldNameEqualTo(String value) {
            addCriterion("FIELD_NAME =", value, "fieldName");
            return (Criteria) this;
        }

        public Criteria andFieldNameNotEqualTo(String value) {
            addCriterion("FIELD_NAME <>", value, "fieldName");
            return (Criteria) this;
        }

        public Criteria andFieldNameGreaterThan(String value) {
            addCriterion("FIELD_NAME >", value, "fieldName");
            return (Criteria) this;
        }

        public Criteria andFieldNameGreaterThanOrEqualTo(String value) {
            addCriterion("FIELD_NAME >=", value, "fieldName");
            return (Criteria) this;
        }

        public Criteria andFieldNameLessThan(String value) {
            addCriterion("FIELD_NAME <", value, "fieldName");
            return (Criteria) this;
        }

        public Criteria andFieldNameLessThanOrEqualTo(String value) {
            addCriterion("FIELD_NAME <=", value, "fieldName");
            return (Criteria) this;
        }

        public Criteria andFieldNameLike(String value) {
            addCriterion("binary FIELD_NAME like", value, "fieldName");
            return (Criteria) this;
        }

        public Criteria andFieldNameNotLike(String value) {
            addCriterion("FIELD_NAME not like", value, "fieldName");
            return (Criteria) this;
        }

        public Criteria andFieldNameIn(List<String> values) {
            addCriterion("FIELD_NAME in", values, "fieldName");
            return (Criteria) this;
        }

        public Criteria andFieldNameNotIn(List<String> values) {
            addCriterion("FIELD_NAME not in", values, "fieldName");
            return (Criteria) this;
        }

        public Criteria andFieldNameBetween(String value1, String value2) {
            addCriterion("FIELD_NAME between", value1, value2, "fieldName");
            return (Criteria) this;
        }

        public Criteria andFieldNameNotBetween(String value1, String value2) {
            addCriterion("FIELD_NAME not between", value1, value2, "fieldName");
            return (Criteria) this;
        }

        public Criteria andValueFieldIsNull() {
            addCriterion("VALUE_FIELD is null");
            return (Criteria) this;
        }

        public Criteria andValueFieldIsNotNull() {
            addCriterion("VALUE_FIELD is not null");
            return (Criteria) this;
        }

        public Criteria andValueFieldEqualTo(String value) {
            addCriterion("VALUE_FIELD =", value, "valueField");
            return (Criteria) this;
        }

        public Criteria andValueFieldNotEqualTo(String value) {
            addCriterion("VALUE_FIELD <>", value, "valueField");
            return (Criteria) this;
        }

        public Criteria andValueFieldGreaterThan(String value) {
            addCriterion("VALUE_FIELD >", value, "valueField");
            return (Criteria) this;
        }

        public Criteria andValueFieldGreaterThanOrEqualTo(String value) {
            addCriterion("VALUE_FIELD >=", value, "valueField");
            return (Criteria) this;
        }

        public Criteria andValueFieldLessThan(String value) {
            addCriterion("VALUE_FIELD <", value, "valueField");
            return (Criteria) this;
        }

        public Criteria andValueFieldLessThanOrEqualTo(String value) {
            addCriterion("VALUE_FIELD <=", value, "valueField");
            return (Criteria) this;
        }

        public Criteria andValueFieldLike(String value) {
            addCriterion("VALUE_FIELD like", value, "valueField");
            return (Criteria) this;
        }

        public Criteria andValueFieldNotLike(String value) {
            addCriterion("VALUE_FIELD not like", value, "valueField");
            return (Criteria) this;
        }

        public Criteria andValueFieldIn(List<String> values) {
            addCriterion("VALUE_FIELD in", values, "valueField");
            return (Criteria) this;
        }

        public Criteria andValueFieldNotIn(List<String> values) {
            addCriterion("VALUE_FIELD not in", values, "valueField");
            return (Criteria) this;
        }

        public Criteria andValueFieldBetween(String value1, String value2) {
            addCriterion("VALUE_FIELD between", value1, value2, "valueField");
            return (Criteria) this;
        }

        public Criteria andValueFieldNotBetween(String value1, String value2) {
            addCriterion("VALUE_FIELD not between", value1, value2, "valueField");
            return (Criteria) this;
        }

        public Criteria andDisplayFieldIsNull() {
            addCriterion("DISPLAY_FIELD is null");
            return (Criteria) this;
        }

        public Criteria andDisplayFieldIsNotNull() {
            addCriterion("DISPLAY_FIELD is not null");
            return (Criteria) this;
        }

        public Criteria andDisplayFieldEqualTo(String value) {
            addCriterion("DISPLAY_FIELD =", value, "displayField");
            return (Criteria) this;
        }

        public Criteria andDisplayFieldNotEqualTo(String value) {
            addCriterion("DISPLAY_FIELD <>", value, "displayField");
            return (Criteria) this;
        }

        public Criteria andDisplayFieldGreaterThan(String value) {
            addCriterion("DISPLAY_FIELD >", value, "displayField");
            return (Criteria) this;
        }

        public Criteria andDisplayFieldGreaterThanOrEqualTo(String value) {
            addCriterion("DISPLAY_FIELD >=", value, "displayField");
            return (Criteria) this;
        }

        public Criteria andDisplayFieldLessThan(String value) {
            addCriterion("DISPLAY_FIELD <", value, "displayField");
            return (Criteria) this;
        }

        public Criteria andDisplayFieldLessThanOrEqualTo(String value) {
            addCriterion("DISPLAY_FIELD <=", value, "displayField");
            return (Criteria) this;
        }

        public Criteria andDisplayFieldLike(String value) {
            addCriterion("DISPLAY_FIELD like", value, "displayField");
            return (Criteria) this;
        }

        public Criteria andDisplayFieldNotLike(String value) {
            addCriterion("DISPLAY_FIELD not like", value, "displayField");
            return (Criteria) this;
        }

        public Criteria andDisplayFieldIn(List<String> values) {
            addCriterion("DISPLAY_FIELD in", values, "displayField");
            return (Criteria) this;
        }

        public Criteria andDisplayFieldNotIn(List<String> values) {
            addCriterion("DISPLAY_FIELD not in", values, "displayField");
            return (Criteria) this;
        }

        public Criteria andDisplayFieldBetween(String value1, String value2) {
            addCriterion("DISPLAY_FIELD between", value1, value2, "displayField");
            return (Criteria) this;
        }

        public Criteria andDisplayFieldNotBetween(String value1, String value2) {
            addCriterion("DISPLAY_FIELD not between", value1, value2, "displayField");
            return (Criteria) this;
        }

        public Criteria andEnabledStatusIsNull() {
            addCriterion("ENABLED_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andEnabledStatusIsNotNull() {
            addCriterion("ENABLED_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andEnabledStatusEqualTo(Short value) {
            addCriterion("ENABLED_STATUS =", value, "enabledStatus");
            return (Criteria) this;
        }

        public Criteria andEnabledStatusNotEqualTo(Short value) {
            addCriterion("ENABLED_STATUS <>", value, "enabledStatus");
            return (Criteria) this;
        }

        public Criteria andEnabledStatusGreaterThan(Short value) {
            addCriterion("ENABLED_STATUS >", value, "enabledStatus");
            return (Criteria) this;
        }

        public Criteria andEnabledStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("ENABLED_STATUS >=", value, "enabledStatus");
            return (Criteria) this;
        }

        public Criteria andEnabledStatusLessThan(Short value) {
            addCriterion("ENABLED_STATUS <", value, "enabledStatus");
            return (Criteria) this;
        }

        public Criteria andEnabledStatusLessThanOrEqualTo(Short value) {
            addCriterion("ENABLED_STATUS <=", value, "enabledStatus");
            return (Criteria) this;
        }

        public Criteria andEnabledStatusIn(List<Short> values) {
            addCriterion("ENABLED_STATUS in", values, "enabledStatus");
            return (Criteria) this;
        }

        public Criteria andEnabledStatusNotIn(List<Short> values) {
            addCriterion("ENABLED_STATUS not in", values, "enabledStatus");
            return (Criteria) this;
        }

        public Criteria andEnabledStatusBetween(Short value1, Short value2) {
            addCriterion("ENABLED_STATUS between", value1, value2, "enabledStatus");
            return (Criteria) this;
        }

        public Criteria andEnabledStatusNotBetween(Short value1, Short value2) {
            addCriterion("ENABLED_STATUS not between", value1, value2, "enabledStatus");
            return (Criteria) this;
        }

        public Criteria andFieldSortIsNull() {
            addCriterion("FIELD_SORT is null");
            return (Criteria) this;
        }

        public Criteria andFieldSortIsNotNull() {
            addCriterion("FIELD_SORT is not null");
            return (Criteria) this;
        }

        public Criteria andFieldSortEqualTo(Short value) {
            addCriterion("FIELD_SORT =", value, "fieldSort");
            return (Criteria) this;
        }

        public Criteria andFieldSortNotEqualTo(Short value) {
            addCriterion("FIELD_SORT <>", value, "fieldSort");
            return (Criteria) this;
        }

        public Criteria andFieldSortGreaterThan(Short value) {
            addCriterion("FIELD_SORT >", value, "fieldSort");
            return (Criteria) this;
        }

        public Criteria andFieldSortGreaterThanOrEqualTo(Short value) {
            addCriterion("FIELD_SORT >=", value, "fieldSort");
            return (Criteria) this;
        }

        public Criteria andFieldSortLessThan(Short value) {
            addCriterion("FIELD_SORT <", value, "fieldSort");
            return (Criteria) this;
        }

        public Criteria andFieldSortLessThanOrEqualTo(Short value) {
            addCriterion("FIELD_SORT <=", value, "fieldSort");
            return (Criteria) this;
        }

        public Criteria andFieldSortIn(List<Short> values) {
            addCriterion("FIELD_SORT in", values, "fieldSort");
            return (Criteria) this;
        }

        public Criteria andFieldSortNotIn(List<Short> values) {
            addCriterion("FIELD_SORT not in", values, "fieldSort");
            return (Criteria) this;
        }

        public Criteria andFieldSortBetween(Short value1, Short value2) {
            addCriterion("FIELD_SORT between", value1, value2, "fieldSort");
            return (Criteria) this;
        }

        public Criteria andFieldSortNotBetween(Short value1, Short value2) {
            addCriterion("FIELD_SORT not between", value1, value2, "fieldSort");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BASE_FIELDS
     *
     * @mbggenerated do_not_delete_during_merge Fri Apr 10 11:28:31 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BASE_FIELDS
     *
     * @mbggenerated Fri Apr 10 11:28:31 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}